

//**  most viewd videos action types
export const GET_MOST_VIEWED_VIDEOS = "GET_MOST_VIEWED_VIDEOS";
export const GET_MOST_VIEWED_VIDEOS_SUCCESS = "GET_MOST_VIEWED_VIDEOS_SUCCESS";
export const GET_MOST_VIEWED_VIDEOS_FAILURE = "GET_MOST_VIEWED_VIDEOS_FAILURE";

